config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("user/", include("user.urls", namespace="user")),
    path("mailinglist/", include("mailinglist.urls", namespace="mailinglist"))

]

mailinglist/urls.py
from django.urls import path
from .views import (MailingListListView, CreateMailingListView, DeleteMailingListView,
   MailingListDetailView, SubscribeToMailingListView, ThankYouForSubscribingView, ConfirmSubscriptionView,
   UnsubscribeView, CreateMessageView, MessageDetailView)

app_name = 'mailinglist'

urlpatterns = [
   path('', MailingListListView.as_view(), name='mailinglist_list') ,
   path('new', CreateMailingListView.as_view(), name='create_mailinglist'),
   path('<uuid:pk>/delete', DeleteMailingListView.as_view(), name='delete_mailinglist'),
   path('<uuid:pk>/manage', MailingListDetailView.as_view(), name='manage_mailinglist'),
   path('<uuid:mailinglist_id>/subscribe', SubscribeToMailingListView.as_view(), name='subscribe'),
   path('<uuid:pk>/thankyou', ThankYouForSubscribingView.as_view(), name='subscriber_thankyou'),
   path('subscribe/confirmation/<uuid:pk>', ConfirmSubscriptionView.as_view(), name='confirm_subscription'),
   path('unsubscribe/<uuid:pk>', UnsubscribeView.as_view(), name='unsubscribe'),
   path('<uuid:mailinglist_id>/message/new', CreateMessageView.as_view(), name='create_message'),
   path('message/<uuid:pk>', MessageDetailView.as_view(), name='view_message')
]

user/urls.py
from django.urls import path
from user import views
from django.contrib.auth import views as auth_views
app_name='user'
urlpatterns = [
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('register', views.RegisterView.as_view(), name="register")
]

mailinglist/models.py
import uuid
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from mailinglist import emails

class MailingList(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=140)
    owner = models.ForeignKey(to=get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse(
            'mailinglist:manage_mailinglist',
            kwargs={'pk':self.id}
        )
    def user_can_use_mailing_list(self, user):
        return user == self.owner   


class Subscriber(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField()
    confirmed  = models.BooleanField(default=False)
    mailing_list = models.ForeignKey(MailingList, on_delete=models.CASCADE)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        is_new = self._state.adding or force_insert
        super().save(force_insert=force_insert, force_update=force_update, using=using,
         update_fields=update_fields)
        if is_new:
            self.send_confirmation_email()
    def send_confirmation_email(self):
        emails.send_confirmation_email(self)
    class Meta:
        unique_together = ['email', 'mailing_list']


class Message(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    mailing_list = models.ForeignKey(MailingList, on_delete=models.CASCADE)
    subject = models.CharField(max_length=140)
    body= models.TextField()
    started = models.DateField(default=None, null=True)
    finished = models.DateField(default=None, null=True)

    

    
    

mailinglist/forms.py
from django import forms
from .models import MailingList, Subscriber, Message
from django.contrib.auth import get_user_model

class SubscriberForm(forms.ModelForm):
    mailing_list = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=MailingList.objects.all(),
        disabled=True
    )
    class Meta:
        model = Subscriber
        fields = ['mailing_list', 'email']


class MessageForm(forms.ModelForm):
    mailing_list = forms.ModelChoiceField(
        widget=forms.HiddenInput, 
        queryset=MailingList.objects.all(),
        disabled=True
    )
    class Meta:
        model = Message
        fields = ['mailing_list', 'subject', 'body']


class MailingListForm(forms.ModelForm):
    owner = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all(),
        disabled=True
    )

    class Meta:
        model = MailingList
        fields = ['owner', 'name']

mailinglist/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (ListView, CreateView, DeleteView, DetailView)
from .models import MailingList, Subscriber, Message
from .forms import MailingListForm, SubscriberForm, MessageForm
from .mixins import UserCanUseMailingList
from django.urls import reverse_lazy, reverse
from django.shortcuts import get_object_or_404, render_to_response
from django.core.exceptions import PermissionDenied

class MailingListListView(LoginRequiredMixin, ListView):
    def get_queryset(self):
        return MailingList.objects.filter(owner=self.request.user)

class CreateMailingListView(LoginRequiredMixin, CreateView):
    form_class = MailingListForm
    template_name = 'mailinglist/mailinglist_form.html'

    def get_initial(self):
        return {
            'owner': self.request.user.id
        }

    
    
class DeleteMailingListView(LoginRequiredMixin, UserCanUseMailingList, DeleteView):
    model = MailingList
    success_url = reverse_lazy('mailinglist:mailinglist_list')


class MailingListDetailView(LoginRequiredMixin, UserCanUseMailingList, DetailView):
    model = MailingList


class SubscribeToMailingListView(CreateView):
    form_class = SubscriberForm
    template_name = 'mailinglist/subcriber_form.html'

    def get_initial(self):
        return {
            'mailing_list': self.kwargs['mailinglist_id']
        }
    def get_success_url(self):
        return reverse(
            'mailinglist:subscriber_thankyou',
            kwargs={
                'pk':self.object.mailing_list.id
            }
        )

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        mailing_list_id = self.kwargs['mailinglist_id']
        ctx["mailing_list"] = get_object_or_404(
            MailingList,
            id=mailing_list_id
        )
        return ctx


class ThankYouForSubscribingView(DetailView):
    model=MailingList
    template_name='mailinglist/subscription_thankyou.html'


class ConfirmSubscriptionView(DetailView):
    model = Subscriber
    template_name = 'mailinglist/confirm_subscription.html'

    def get_object(self, queryset=None):
        subcriber = super().get_object(queryset=queryset)
        subcriber.confirmed = True
        subcriber.save()
        return subcriber


class UnsubscribeView(DeleteView):
    model = Subscriber
    template_name='mailinglist/unsubscribe.html'
    def get_success_url(self):
        mailing_list = self.object.mailing_list
        # probable here 
        return reverse(
            'mailinglist:subscribe',
            kwargs={'mailinglist_id': mailing_list.id}
        )


class CreateMessageView(LoginRequiredMixin ,CreateView):
    form_class = MessageForm
    template_name = 'mailinglist/message_form.html'
    SAVE_ACTION = 'save'
    PREVIEW_ACTION = 'preview'

    def get_success_url(self):
        return reverse(
            'mailinglist:manage_mailinglist',
            kwargs = {'pk': self.object.mailing_list.id}
        )

    def get_initial(self):
        return {
            'mailing_list': self.get_mailing_list()
        }

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        mailing_list = self.get_mailing_list()
        ctx.update(
            {'mailing_list': mailing_list,
            'SAVE_ACTION': self.SAVE_ACTION,
            'PREVIEW_ACTION': self.PREVIEW_ACTION}
        )
        return ctx

    def form_valid(self, form):
        action = self.request.POST.get('action')
        if action == self.SAVE_ACTION:
            context = self.get_context_data(form=form, message=form.instance)
            return self.render_to_response(context=context)
        elif action == self.PREVIEW_ACTION:
            return super().form_valid(form)

    def get_mailing_list(self):
        mailing_list = get_object_or_404(MailingList,
        id=self.kwargs['mailinglist_id'])
        if not mailing_list.user_can_use_mailing_list(self.request.user):
            raise PermissionDenied
        return mailing_list

    
class MessageDetailView(LoginRequiredMixin, UserCanUseMailingList,DetailView):
    model = Message

mailinglist/templates/mailinglist/confirm_subscription.html
{%extends 'base.html' %} 
{% block title %} subscription to {{mailinglist}} confirmed. {% endblock %} 
{% block body%}
<h1>Subscription to {{mailinglist}} confirmed !</h1>

mailinglist/templates/mailinglist/mailinglist_confirm_delete.html
{% extends 'base.html' %} 


{%block body%} 
<h1>Confirm Delete ?</h1>
<form action="" method="post">
    {%csrf_token%} 
    <p>Are you sure you want to delete {{mailinglist.name}} ?</p> 
    <input type="submit" value="yes" class="btn btn-danger btn-sm">
    <a href="{%url 'mailinglist:manage_mailinglist' mailinglist.id %}" class="btn btn-primary btn-lg">No</a>
</form>
{% endblock%} 

mailinglist/templates/mailinglist/mailinglist_detail.html
{% extends 'base.html' %} 
{% block title %} {{mailinglist.name}} management {% endblock%} 

{% block body%} 
<h1>{{mailinglist.name}} management 
    <a href="{% url 'mailinglist:delete_mailinglist' pk=mailinglist.id%}" class="btn btn-danger">
        Delete
    </a></h1>
<div>
    <a href="{% url 'mailinglist:subscribe' mailinglist_id=mailinglist.id %}">Subscription Link</a>
</div>
<h2>Messages</h2>
<div>
    Send new
    <a href="{% url 'mailinglist:create_message' mailinglist_id=mailinglist.id%}" class="btn btn-primary">Send new message</a>
</div>
<ul>
    {%for message in mailinglist.message_set.all%} 
    <li>
        <a href="{% url 'mailinglist:view_message' pk=message.id%}">{{message.subject}}</a>
    </li>
    {% endfor %}
</ul>
<h2>Subscribers</h2>
<ul>
    {% for subscriber in mailinglist.subscriber_set.all %}
    <li>
        {{subscriber.email}}
        {{subscriber.confirm|yesno:"confirmed, unconfirmed"}}
        <a href="{% url 'mailinglist:unsubscribe' %}"></a>
    </li>
    {%endfor%}
</ul>
{%endblock%} 

mailinglist/templates/mailinglist/mailinglist_form.html
{%extends 'base.html' %} 
{% load crispy_forms_tags %} 

{% block title %} create mailing list {% endblock %} 

{% block body %} 
<h1>Create Mailing List</h1> 
<form method="post" class="col-sm-4">
    {% csrf_token %} 
    {{form | crispy }}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %} 

mailinglist/templates/mailinglist/mailinglist_list.html
{% extends 'base.html' %} 
{% block title %} Your mailing lists {% endblock%} 

{% block body %} 
<div class="row user mailing_lists">
    <div class="col-sm-12">
        <h1>Your mailing lists</h1>
        <div>
            <a href="{% url 'mailinglist:create_mailinglist' %}" class="btn btn-primary">
                New list
            </a>
        </div>
        <p>Your mailing lists:</p> 
        <ul class="mailing_list_list">
            {% for mailinglist in mailinglist_list %} 
            <li class="mailinglist-item">
                <a href="{% url 'mailinglist:manage_mailinglist' pk=mailinglist.id %}"> {{mailinglist.name}} </a>
            </li>
            {%endfor%} 
        </ul>
    </div>
</div>
{% endblock%} 

mailinglist/templates/mailinglist/message_detail.html
{% extends 'base.html' %} 
{% laod mardownify %} 
{% title %} {{message.subject}} {% endblock %} 
{% block body %} 
<h1>{{message.subject}}</h1>
<div>
    {{message.body | markdownify}}
</div>

mailinglist/templates/mailinglist/message_form.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %} 
{% load markdownify %} 
{%block body %} <h1>Send a message to {{mailing_list.name}}</h1>
{% if message %} 
<div class="card">
    <div class="card-header">
        Message Preview
    </div>
    <div class="card-body">
        <h5 class="card-title">{{message.subject}}</h5>
        <div>{{message | markdownify }}</div> 
    </div>
</div>
{% endif %} 
<form class="col-sm-12 col-md-9" method="post" >
    {% csrf_token %} 
    {{form | crispy}}
    <button type="submit" name="action" class="btn btn-primary" value="{{SAVE_ACTION}}">Save</button>
    <button type="submit" name="action" class="btn btn-primary" value="{{PREVIEW_ACTION}}">Preview</button>
</form>
{% endblock %}

mailinglist/templates/mailinglist/subcriber_form.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %} 
{% block title%} Suscribe to {{mailing_list}} {% endblock %} 
{% block body %} 
<h1>Suscribe to {{mailing_list}}</h1>
<form action="" method="post">
    {%csrf_token %} 
    {{form | crispy}} 
    <button class="btn btn-primary" type="submit">Submit</button>
</form>
{%endblock%}

mailinglist/templates/mailinglist/subscription_thankyou.html
{% extends 'base.html' %} 
{% block title % } Thank you for subscribing to {{mailinglist}} {% endblock%} 

{% block body %} 
<div class="col-sm-12">
    <h1>Thank you for subscribing to {{mailinglist}}</h1>
    <p>Check your email for a confirmation email.</p>
</div>
{% endblock%} 

mailinglist/templates/mailinglist/unsubscribe.html
{%extends 'base.html' %} 
{% block title %} Unsubscribe ? {%endblock%} 
{%block body %} 
<div class="col">
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to unsubscribe to {{subscriber.mailing_list.name}}</p>
        <input value="yes, i want to unsubscribe" class="btn btn-danger">
    </form>
</div>
{%endblock%}