config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("user/", include("user.urls", namespace="user")),
    path("mailinglist/", include("mailinglist.urls", namespace="mailinglist"))

]

mailinglist/urls.py
from django.urls import path
from .views import (MailingListListView, CreateMailingListView, DeleteMailingListView,
   MailingListDetailView, SubscribeToMailingListView, ThankYouForSubscribingView, ConfirmSubscriptionView,
   UnsubscribeView, CreateMessageView, MessageDetailView)

app_name = 'mailinglist'

urlpatterns = [
   path('', MailingListListView.as_view(), name='mailinglist_list') ,
   path('new', CreateMailingListView.as_view(), name='create_mailinglist'),
   path('<uuid:pk>/delete', DeleteMailingListView.as_view(), name='delete_mailinglist'),
   path('<uuid:pk>/manage', MailingListDetailView.as_view(), name='manage_mailinglist'),
   path('<uuid:mailinglist_id>/subscribe', SubscribeToMailingListView.as_view(), name='subscribe'),
   path('<uuid:pk>/thankyou', ThankYouForSubscribingView.as_view(), name='subscriber_thankyou'),
   path('subscribe/confirmation/<uuid:pk>', ConfirmSubscriptionView.as_view(), name='confirm_subscription'),
   path('unsubscribe/<uuid:pk>', UnsubscribeView.as_view(), name='unsubscribe'),
   path('<uuid:mailinglist_id>/message/new', CreateMessageView.as_view(), name='create_message'),
   path('message/<uuid:pk>', MessageDetailView.as_view(), name='view_message')
]

user/urls.py
from django.urls import path
from user import views
from django.contrib.auth import views as auth_views
app_name='user'
urlpatterns = [
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('register', views.RegisterView.as_view(), name="register")
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <title> {% block title %} {% endblock %}</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    </head>
    <body>
        <div class="container">
            <nav class="navbar navbar-light bg-light">
            <a href="#" class="navbar-brand">Mail Ape</a>
            <ul class="navbar-nav">
                <li class="navbar-item">
                    <a href="{% url 'mailinglist:mailinglist_list' %}" class="navbar-link">
                        Your  mailing lists
                    </a>
                </li>
                {% if request.user.is_authenticated %} 
                <li class="nav-item">
                    <a href="{% url 'user:logout' %}" class="nav-link">Logout</a>
                </li>
                {%else %}
                <li class="nav-item">
                    <a href="{% url  'user:login' %}" class="nav-link">Your mailing lists</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'user:register' %}" class="nav-link">Your mailing lists</a>
                </li>
                {% endif %}
            </ul>
            </nav>
            {% block body %} 
            {% endblock %} 
        </div>
    </body>
</html>